### PR TITLE
Week 2 work

### PR DESCRIPTION
**Pull request by LivsWorld**
I'm following the step-1-servlets-walkthrough of Week 2's content. I changed the server message so it says "Hello Olivia" when you press the link on the home page.

### CODE REVIEW

**Comment by LivsWorld** [comment]
On to step 2 of the Week 2 walkthrough. Now my webpage displays a message from the HelloWorldServlet when the "See Message" button is clicked.

Screen Shot 2022-06-12 at 4 43 53 PM

**Comment by LivsWorld** [comment]
I'm halfway through step 3 of the week 2 walkthrough. When HelloWorldServlet receives a GET request (whenever "/hello" is accessed) it converts an ArrayList of messages into a JSON string and sends it to the client. I tested and the client correctly receives the JSON string:

Screen Shot 2022-06-13 at 1 14 43 PM

**Comment by LivsWorld** [comment]
Finished step 3 of week 2's walkthrough. The client receives a JSON string of messages, then script.js converts this into an array of strings, chooses a message at random index, and displays the message when "Find Out!" is clicked.

Screen Shot 2022-06-13 at 2 15 36 PM

**Comment by LivsWorld** [comment]
I created a separate contact page at "contact.html" for visitors to share their contact info. When submit is pressed, the client sends a POST request to "FormHandlerServlet.java" at the "form-handler" URL. The servlet prints the submitted name, email, and message to Logs for recording, then redirects back to the home page.
Screen Shot 2022-06-14 at 11 41 25 AM
Screen Shot 2022-06-14 at 11 42 29 AM

**Review by jdtyner — APPROVED** [review]
Looks good! I appreciate the comments and screenshots on the PR.

**Pull request merged**
