### PR TITLE
Add Datastore storage to FormHandlerServlet.java

### PR DESCRIPTION
**Pull request by LivsWorld**
I modified FormHandlerServlet.java to save contact information submitted through the form in contact.html to Datastore. When the user clicks submit, contact.html sends a request to the servlet with the input information. The servlet creates an Entity of kind "Contact" and puts it into the Datastore database for persistent storage. I deployed these changes and it works as expected. Here's the view inside Datastore:
Screen Shot 2022-06-14 at 5 11 45 PM

### CODE REVIEW

**Comment by LivsWorld** [comment]
I've modified FormHandlerServlet.java so it loads the contact information submitted by the user to display on a "/form-handler" webpage. I use the key generated when creating the Contact entity as part of a Query on Datastore. This should return a results list to the servlet containing only the contact just created by that user. The servlet converts the contact info into a JSON and displays it (for testing purposes).
Screen Shot 2022-06-16 at 9 47 46 AM

**Comment by LivsWorld** [comment]
I added a navigation bar and some CSS formatting to my portfolio, so the content is divided into 4 different pages: About, Projects, Fun, and Contact. "About" displays index.html and I plan on adding links to Github and LinkedIn under my photo. "Projects" is currently empty and I plan to add tiles to the page representing my projects. "Fun" has the button that fetches a random message from the server and I plan on adding pictures associated with each random message. "Contact" has the contact form and I plan to add some formatting.
Screen Shot 2022-06-20 at 10 17 24 AM
Screen Shot 2022-06-20 at 10 18 06 AM
Screen Shot 2022-06-20 at 10 18 58 AM

**Comment by LivsWorld** [comment]
I ran into difficulties accessing the JSON string sent by FormHandlerServlet.java from the client end. In [Modify contact.html form to trigger JS function on submit](https://github.com/LivsWorld/software-product-sprint/pull/4/commits/e610956d62b22b1ff8c99fc8d50344fd347eca7a) I changed the `action` attribute of the form to `"#"` and `onsubmit` to `"submitHandler(this)"`. The idea was that submitHandler() would send a POST request to FormHandlerServlet.java and receive a JSON with the form information. Then, it would parse and display the information, similar to the Week 2 tutorial. Instead, when I pressed submit, it would reload contact.html with the form info as URL search parameters. After talking asking a Googler through office hours, I decided to narrow the scope of what I was trying to do so I could finish an MVP portfolio. Now, FormHandlerServlet.java redirects to a page called thanks.html and passes the user's name as a URL search parameter. On the client end, I plan on reading this info and displaying a message with the user's name.
Screen Shot 2022-06-20 at 10 41 45 AM

**Comment by LivsWorld** [comment]
I modified projects.html so cards representing my projects would display in a gallery format:
Screen Shot 2022-06-20 at 2 43 59 PM

**Review by jdtyner — APPROVED** [review]
Amazing

**Pull request merged**
